### ISSUE TITLE
这是什么？

### ISSUE THREAD

**Issue by scientificworld** [z1h/z1h#2]
我不小心输入了一个/字符，结果显示：
`Runtime exception: {"file":"/Users/zwr/Documents/zwr/golang/src/zwei.ren/z1h/repl/exec/exec.go","line":112,"msg":"/ left or right empty"}`
可是我没看到/users文件夹里多出来什么啊？？？
系统版本（`uname -a`)：`Darwin MacBook.lan 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

**Comment by z1h** [comment]
抱歉, 这个报错信息是编译错误, 有意义的部分仅为"/ left or right empty", 也就是除号的左值或右值为空
那个/Users/...是底层环境的错误, 和你的运行环境没有关系, 下次更新将会把这部分不必要的信息去掉

谢谢反馈!

**Comment by scientificworld** [comment]
不用谢^_^
我再提个建议，ruby的repl -> irb里面，好像可以在输入时也高亮，能不能增加一下这个功能？（虽然我也不知道怎么实现。。）

**Comment by z1h** [comment]
> 不用谢^_^
> 我再提个建议，ruby的repl -> irb里面，好像可以在输入时也高亮，能不能增加一下这个功能？（虽然我也不知道怎么实现。。）

经过各方面的比较之后, 发现终端repl的支持是一项需要投入大量时间的工作, 主要是多平台下很难保持一致. 所以目前考虑是采用web页面来做repl:

1. 使用 z1h -web 30000 来开启z1h的Web模式, 30000是端口号
2. 访问http://127.0.0.1:30000/z1h, 填入从终端显示文本复制的`Web repl page username[admin??] password[??????]`中的用户名和密码
