### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by scientificworld** [z1h/z1h#3]
现在repl里似乎没法退出？
能不能加一个类似于exit的命令？谢谢

**Comment by z1h** [comment]
> 现在repl里似乎没法退出？
> 能不能加一个类似于exit的命令？谢谢

你好, 可以通过 `Ctrl+C` 或者 `Ctrl+D` 退出repl模式, 也可以通过输入go的代码 `os.Exit(0)` 来退出进程. 还是比较建议使用web repl的模式哈

**Comment by scientificworld** [comment]
哦，忘记z1h能直接调用go的库了。。谢谢啊

**Comment by scientificworld** [comment]
web repl好像输入了os.Exit(0)之后就会直接退出诶……没法reboot了？？

**Comment by z1h** [comment]
> web repl好像输入了os.Exit(0)之后就会直接退出诶……没法reboot了？？

是的, os.Exit是退出了整个进程, web服务也就终止了

**Comment by z1h** [comment]
> web repl好像输入了os.Exit(0)之后就会直接退出诶……没法reboot了？？

web repl的'Reboot'其实只是重置当前的session, 例如变量等, 不是重启进程

**Comment by scientificworld** [comment]
这算是bug还是正常现象？

**Comment by z1h** [comment]
> 这算是bug还是正常现象？

正常的, web repl是作为终端命令行的替代品, 权限很高的, 可以直接终止进程. 你可以用supervisor等工具守护z1h进程

**Comment by scientificworld** [comment]
好的，感谢回复
p.s. 有没有打算做编辑器插件？没有高亮写起来不太方便

**Comment by z1h** [comment]
> 好的，感谢回复
> p.s. 有没有打算做编辑器插件？没有高亮写起来不太方便

在IDE方面, 现在采用的方案如下:
[https://www.z1h.org/doc/zh/017.html](https://www.z1h.org/doc/zh/017.html)

使用Sublime:

- [https://www.sublimetext.com/3](https://www.sublimetext.com/3)
- 下载并安装
- 将一个`.z1h`后缀名的文件拖拽进Sublimt Text面板
- 在上方菜单栏选择

`View` > `Syntax` > `Open all with current...` > `JavaScript` > `JavaScript`

**Comment by scientificworld** [comment]
用js的插件吗？
那么vim的解决方案就是:set filetype=javascript了
试了一下，确实可以高亮一部分

**Comment by z1h** [comment]
> 用js的插件吗？
> 那么vim的解决方案就是:set filetype=javascript了
> 试了一下，确实可以高亮一部分

是的, Z1h兼容绝大多数js的语法

**Comment by scientificworld** [comment]
好像用typescript的插件可以兼容更多语法（比如print）……
仅限vim，其他编辑器就不知道了
毕竟ts是js的超集

**Comment by z1h** [comment]
> 好像用typescript的插件可以兼容更多语法（比如print）……
> 仅限vim，其他编辑器就不知道了
> 毕竟ts是js的超集

好的, 我后面空出手来也考虑做一下这方面的工作, 例如用一些Web Editor + File Explorer来把web repl做好

**Comment by scientificworld** [comment]
那就不是web repl了，是web ide了【笑
